# Generated by Django 3.1.3 on 2020-12-04 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECH',
            fields=[
                ('HORD', models.AutoField(db_column='HORD', primary_key=True, serialize=False, verbose_name='Order Number')),
                ('HEDTE', models.DateField(db_column='HEDTE', verbose_name='Entered Date')),
                ('HSTS', models.CharField(choices=[('ONGOING', 'ONGOING'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], db_column='HSTS', max_length=10, verbose_name='Order Status')),
                ('HCUST', models.ForeignKey(db_column='HCUST', on_delete=django.db.models.deletion.CASCADE, related_name='Cust', to=settings.AUTH_USER_MODEL, verbose_name='Customer No')),
                ('HSHOP', models.ForeignKey(db_column='HSHOP', on_delete=django.db.models.deletion.CASCADE, related_name='Shop', to=settings.AUTH_USER_MODEL, verbose_name='Shop No')),
            ],
        ),
        migrations.CreateModel(
            name='ECL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LLINE', models.DecimalField(db_column='LLINE', decimal_places=0, max_digits=3, verbose_name='Line number')),
                ('LPROD', models.CharField(db_column='LPROD', max_length=200, verbose_name='Item')),
                ('LQORD', models.DecimalField(db_column='LQORD', decimal_places=0, max_digits=3, verbose_name='Ordered Quantity')),
                ('LPRIC', models.DecimalField(db_column='LPRIC', decimal_places=2, max_digits=4, verbose_name='Price')),
                ('LDISC', models.DecimalField(db_column='LDISC', decimal_places=2, max_digits=4, verbose_name='Discount')),
                ('LORD', models.ForeignKey(db_column='LORD', on_delete=django.db.models.deletion.CASCADE, to='orderapp.ech', verbose_name='Order Number')),
            ],
        ),
    ]
