# Generated by Django 3.1.3 on 2020-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20201205_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecl',
            name='LDISC',
            field=models.DecimalField(db_column='LDISC', decimal_places=2, max_digits=6, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='ecl',
            name='LPRIC',
            field=models.DecimalField(db_column='LPRIC', decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
    ]
