# Generated by Django 3.1.3 on 2020-11-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ratings', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('baggit_support', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopkeeperapp.category')),
                ('shopid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shop Profiles',
            },
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('uom', models.CharField(max_length=25, null=True, verbose_name='Unit of Measure')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shop Items',
            },
        ),
    ]
