# Generated by Django 3.1.4 on 2020-12-06 20:02

from django.db import migrations, models
import shopkeeperapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='category/default.jpg', upload_to=shopkeeperapp.models.upload_to, verbose_name='Image'),
        ),
    ]
