# Generated by Django 3.1.4 on 2020-12-09 23:46

from django.db import migrations, models
import shopkeeperapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeperapp', '0002_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default/category.jpg', upload_to=shopkeeperapp.models.upload_to, verbose_name='Image'),
        ),
    ]
