# Generated by Django 3.1.4 on 2020-12-18 03:59

from django.db import migrations, models
import shopkeeperapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeperapp', '0003_auto_20201210_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='media/default/category_ngqsdm.jpg', upload_to=shopkeeperapp.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
